name: dependabot-pr-merge
on:
  workflow_call:
    inputs:
      pr_number:
        description: "The PR number"
        default: ""
        required: true
        type: string

jobs:
  automerge:
    name: Merge Dependabot Pull Pequest
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Merge
        uses: actions/github-script@v5
        with:
          debug: true
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var pr_number = ${{ inputs.pr_number }}
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              merge_method: 'squash'
            })
