name: dependabot-pr-merge
on:
  workflow_call:
    inputs:
      pr_number:
        description: "The PR number"
        default: "191"
        required: true
        type: string
  workflow_run:
    workflows: ["run-tests"]
    types:
      - completed

jobs:
  automerge:
    name: Merge Dependabot Pull Pequest
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Merge
        uses: actions/github-script@v5
        with:
          pull_number: ${{ inputs.pr_number }}
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: $INPUT_PULL_NUMBER,
              merge_method: 'squash'
            })
