name: dependabot-pr-merge
on:
  workflow_call:
    inputs:
      pr_number:
        description: "The PR number"
        default: ""
        required: true
        type: string

jobs:
  automerge:
    name: Merge Dependabot Pull Pequest
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: actions/github-script@v5
        with:
          pull_number: ${{ inputs.pr_number }}
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var pr-number = ${{ env.INPUT_PULL_NUMBER }}
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr-number,
              merge_method: 'squash'
            })
